docs/platform/02-client.md
Adding two new projects to the 'Third-Party Clients' section:
- Ruby Client: [gbaptista/mistral-ai](https://github.com/gbaptista/mistral-ai)
- CLI Multi-Provider Client: [icebaker/nano-bots](https://github.com/icebaker/ruby-nano-bots)
=> Adding two new projects to the 'Third-Party Clients' section

docs/getting-started/clients.mdx
Hello. A few days ago, I released [a Ruby client](https://github.com/wilsonsilva/mistral). It is a 1:1 Python client port of the official client-python.
- It has API parity with the official Python client (https://github.com/mistralai/client-python)
- It is the only Ruby client with the exact same error handling, retry mechanisms and configuration options as the Python client
- It is the only Ruby client that __supports functions__
- It only has __two__ dependencies
- It is __fully typed__, avoiding primitive obsession
- It implements the same examples
Here's a brief implementation of chat stream using the official Python client and using my Ruby clent:
```python
client = MistralClient(api_key=os.environ["MISTRAL_API_KEY"])
response = client.chat_stream(
model="mistral-small", …
```
=> Add the 1:1 port to Ruby of the official Python client to the client list

docs/getting-started/clients.mdx
This PR adds a Dart client to the platform docs under Third-Party Clients. It can be used in both pure Dart and Flutter applications.
Link to the official package repository page https://pub.dev/packages/mistralai_client_dart
Link to the Github page https://github.com/nomtek/mistralai_client_dart
This is the same PR as https://github.com/mistralai/platform-docs-public/pull/30 but I had to reopen it to fix merge conflicts.
=> Add third party Dart client to the platform docs

openapi.yaml
Fixes #12 
Ensures that libraries know that the API uses bearer token authentication across all endpoints.
=> Adding security schemas to opeanapi spec

docs/getting-started/glossary.mdx
Corrected the misspelling of the word "hallucination" in the glossary entry for RAG. The previous text incorrectly spelled it as "halluciation."
=> fix: Correct misspelling of "halluciation"

docs/capabilities/code-generation.mdx
Corrected the typo in the word 'environment' within the LangChain integration example.
=> fix: correct typo in 'environment'

docs/capabilities/completion.mdx
Corrected "lanugage" to "language".
=> fix: correct typo in text generation guide

docs/capabilities/embeddings.mdx
Corrected the typo in the paraphrase detection section for clarity. The sentence now correctly reads: "The result suggests that the first two sentences are semantically similar and could be potential paraphrases, whereas the third sentence is more different." This ensures the description accurately reflects the semantic similarity between sentences.
=> fix: correct typo in paraphrase detection section

docs/getting-started/clients.mdx, docs/guides/basic-RAG.md
This PR adds the Vercel AI SDK to:
-  the clients page (as a JavaScript / TypeScript library) 
- to the Basic RAG Guide page
=> docs: add Vercel AI SDK

docs/capabilities/completion.mdx
Corrected a typo in the text generation documentation where "models allows" was changed to "models allow". This ensures grammatical accuracy and clarity in the description of Mistral models.
=> Fix: typo "models allows" to "models allow" in documentation

docs/getting-started/models/overview.md
Fixes blog post links for the new Codestral and Mistral small models.
=> fix: blog post links in model overview

docs/capabilities/code-generation.mdx
There has been some progress lately on the former `jupyterlab-codestral` extension, which enables using Codestral in a Jupyter environment in the browser directly.
`jupyterlab-codestral` has been renamed to `@jupyterlite/ai` since it now supports other providers too.
It is still possible to configure it to use `MistralAI` as the provider:
=> Update link to the JupyterLite demo

docs/capabilities/embeddings.mdx
Corrected the phrase "Let's take a look of the length of the first embedding:" to "Let's take a look at the length of the first embedding:" in the embeddings guide.
=> -fix: change "look of" to "look at" in embeddings guide

src/components/HomepageFeatures/index.tsx
Corrected the phrase "top level team of researchers" to "top-level team of researchers" by adding a hyphen for proper compound adjective usage. This ensures clarity and adherence to standard grammatical conventions.
=> Fix: Add hyphen to 'top-level' in feature description

docusaurus.config.js
Corrected the spelling of "internalization" to "internationalization" in the Docusaurus configuration file to ensure proper terminology for setting metadata for different languages.
=> Fix typo in Docusaurus configuration file

docs/capabilities/function-calling.mdx
Corrected the typo "speficy" to "specify" in the "Function Calling" guide.
=> fix: typo in function_calling guide

docs/capabilities/code-generation.mdx
Fixed an extra space before the question mark in the endpoint usage section.
=> docs: Remove extra space before question mark

docs/guides/finetuning_sections/_04_faq.md
Corrected the typo in the FAQ section regarding the recommended learning rate for LoRA fine-tuning. Changed "recommended" to "recommend" for accurate grammar.
=> fix: typo in Learning Rate Recommendation Section

docs/capabilities/guardrailing.mdx
👋, this fix is for a small typo in [Guardrailing section](https://docs.mistral.ai/capabilities/guardrailing/) for the Javascript library. 
```diff
const chatResponse = await client.chat(
model: 'mistral-large-latest',
messages: [{role: 'user', content: 'What is the best French cheese?'}],
-   safe_prompt: true
+   safePrompt: true
);
```
=> Fix typo in JS Guardrailing

docs/capabilities/OCR/annotations.md
Just happened upon this typo when reading through the docs and wanted to propose a quick fix:
```markdown
You can also add a `description` key in you `properties` object.
```
The `you` should be `your`
=> fix(docs): correct typo in annotations.md
